version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5076:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - easydonate-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - easydonate-network

networks:
  easydonate-network:
    driver: bridge